### PR TITLE
Clean up testcase for relayedTransactionV2Builder

### PR DESCRIPTION
**Pull request by MWFIAE**
The sender of the innerTransaction is Bob as he will later sign the transaction. The sender is overwritten anyways so it doesn't matter much in terms of results, but it's confusing for people wanting to learn about the relayedTransactionV2Builder :)

### CODE REVIEW

**Review by bogdan-rosianu — APPROVED** [review]
Yup, thanks for your contribution ! :100:

**Review by schimih — DISMISSED** [review]

**Comment by MWFIAE** [comment]
@bogdan-rosianu 
Please check again 🙏

**Comment by bogdan-rosianu** [comment]
package-lock check is still failing

**Review by andreibancioiu — APPROVED** [review]

**Review by bogdan-rosianu — APPROVED** [review]

**Comment by bogdan-rosianu** [comment]
Thanks for the finding! I will close this PR as it has been re-done in #244 (with signed commits and proper package-lock)

**Pull request closed without merging**
